DROP TABLE HOTEL;
DROP TABLE ROOM;
DROP TABLE BOOKING;
DROP TABLE USERS;
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
id_category INTEGER CONSTRAINT PK_ID_CATEGORY PRIMARY KEY,
category_stars INTEGER
);

CREATE TABLE HOTEL(
id_hotel INTEGER CONSTRAINT PK_ID_HOTEL PRIMARY KEY,
hotel_name VARCHAR2(100),
hotel_address VARCHAR2(100),
hotel_city VARCHAR2(100),
hotel_rating FLOAT,
id_category INTEGER,
CONSTRAINT FK_ID_CATEGORY FOREIGN KEY (id_category) REFERENCES CATEGORY(id_category)
);

CREATE TABLE ROOM(
id_room INTEGER CONSTRAINT PK_ID_ROOM PRIMARY KEY,
room_type VARCHAR2(30),
room_price FLOAT,
total_rooms INTEGER,
id_hotel INTEGER,
CONSTRAINT FK_ID_HOTEL FOREIGN KEY (id_hotel) REFERENCES HOTEL(id_hotel)
);

CREATE TABLE USERS(
id_user INTEGER CONSTRAINT PK_ID_USER PRIMARY KEY,
username VARCHAR2(30),
password VARCHAR2(30),
email VARCHAR2(50),
personal_name VARCHAR2(100),
user_address VARCHAR2(100),
user_tlp VARCHAR2(30),
user_role VARCHAR2(30)
);

CREATE TABLE BOOKING(
id_booking INTEGER CONSTRAINT PK_ID_BOOKING PRIMARY KEY,
in_date DATE,
out_date DATE,
room_number INTEGER,
pay_state VARCHAR2(30),
pay_method VARCHAR2(30),
id_user INTEGER,
id_room INTEGER,
CONSTRAINT FK_ID_USER FOREIGN KEY (id_user) REFERENCES USERS(id_user),
CONSTRAINT FK_ID_ROOM FOREIGN KEY (id_room) REFERENCES ROOM(id_room)
);


--AUTOINCREMENT USER

CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TR_ID_USER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT SEQ_USER.NEXTVAL INTO :new.id_user FROM dual;
END;
/

--AUTOINCREMENT HOTEL

CREATE SEQUENCE SEQ_HOTEL
START WITH 100
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TR_ID_HOTEL
BEFORE INSERT ON HOTEL
FOR EACH ROW
BEGIN
    SELECT SEQ_HOTEL.NEXTVAL INTO :new.id_hotel FROM dual;
END;
/

--AUTOINCREMENT ROOM

CREATE SEQUENCE SEQ_ROOM
START WITH 200
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TR_ID_ROOM
BEFORE INSERT ON ROOM
FOR EACH ROW
BEGIN
    SELECT SEQ_ROOM.NEXTVAL INTO :new.id_room FROM dual;
END;
/

--AUTOINCREMENT CATEGORY

CREATE SEQUENCE SEQ_CATEGORY
START WITH 300
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TR_ID_CATEGORY
BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
    SELECT SEQ_CATEGORY.NEXTVAL INTO :new.id_category FROM dual;
END;
/

--AUTOINCREMENT BOOKING

CREATE SEQUENCE SEQ_BOOKING
START WITH 400
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TR_ID_BOOKING
BEFORE INSERT ON BOOKING
FOR EACH ROW
BEGIN
    SELECT SEQ_BOOKING.NEXTVAL INTO :new.id_booking FROM dual;
END;
/

BEGIN
    alter table "CHOOMUSER"."ROOM" add constraint FK_HOTEL foreign key("ID_HOTEL") references "HOTEL"("ID_HOTEL") ON DELETE CASCADE;
    
    alter table "CHOOMUSER"."BOOKING" add constraint FK_ROOM foreign key("ID_ROOM") references "ROOM"("ID_ROOM") ON DELETE CASCADE;
    
    alter table "CHOOMUSER"."BOOKING" add constraint FK_USER foreign key("ID_USER") references "USERS"("ID_USER") ON DELETE CASCADE;

    COMMIT;

END;
